// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace RainPredictionML.Model
{
    public class ModelInput
    {
        [ColumnName("Date"), LoadColumn(0)]
        public string Date { get; set; }


        [ColumnName("1998"), LoadColumn(1)]
        public float Col1998 { get; set; }


        [ColumnName("1999"), LoadColumn(2)]
        public float Col1999 { get; set; }


        [ColumnName("2000"), LoadColumn(3)]
        public float Col2000 { get; set; }


        [ColumnName("2001"), LoadColumn(4)]
        public float Col2001 { get; set; }


        [ColumnName("2002"), LoadColumn(5)]
        public float Col2002 { get; set; }


        [ColumnName("2003"), LoadColumn(6)]
        public float Col2003 { get; set; }


        [ColumnName("2004"), LoadColumn(7)]
        public float Col2004 { get; set; }


        [ColumnName("2005"), LoadColumn(8)]
        public float Col2005 { get; set; }


        [ColumnName("2006"), LoadColumn(9)]
        public float Col2006 { get; set; }


        [ColumnName("2007"), LoadColumn(10)]
        public float Col2007 { get; set; }


        [ColumnName("2008"), LoadColumn(11)]
        public float Col2008 { get; set; }


        [ColumnName("2009"), LoadColumn(12)]
        public float Col2009 { get; set; }


        [ColumnName("2010"), LoadColumn(13)]
        public float Col2010 { get; set; }


        [ColumnName("2011"), LoadColumn(14)]
        public float Col2011 { get; set; }


        [ColumnName("2012"), LoadColumn(15)]
        public float Col2012 { get; set; }


        [ColumnName("2013"), LoadColumn(16)]
        public float Col2013 { get; set; }


        [ColumnName("2014"), LoadColumn(17)]
        public float Col2014 { get; set; }


        [ColumnName("2015"), LoadColumn(18)]
        public float Col2015 { get; set; }


        [ColumnName("2016"), LoadColumn(19)]
        public float Col2016 { get; set; }


        [ColumnName("2017"), LoadColumn(20)]
        public float Col2017 { get; set; }


    }
}
